#!/bin/bash
# run_all.sh — submit one GPU + one CPU + one post-compute SLURM job per disease.
# CPU depends on GPU (afterok); post-compute depends on CPU (afterok).
# Post-compute runs CIs, NHANES eval, dashboard, and forest plot.
#
# Usage:
#   bash run_all.sh               # live submission
#   bash run_all.sh --dry-run     # print sbatch commands, no submission
#   bash run_all.sh --purge       # wipe data/ + results/, then submit all jobs
#   bash run_all.sh --purge --dry-run  # show what would be deleted + printed, no action

CONF_DIR="conf/disease"
SPLIT_SALT=${SPLIT_SALT:-""}
NHANES_DIR=${NHANES_DIR:-data/nhanes}
EHRSHOT_KEY_FILE=${EHRSHOT_KEY_FILE:-""}
DRY_RUN=0
PURGE=0

for arg in "$@"; do
    [[ "$arg" == "--dry-run" ]] && DRY_RUN=1
    [[ "$arg" == "--purge"   ]] && PURGE=1
done

# ── Purge ─────────────────────────────────────────────────────────────────────
if [[ "$PURGE" == "1" ]]; then
    echo "=== PURGE ==="
    echo "Will permanently delete:"
    echo "  data/*           (modeling CSVs, EHRSHOT CSVs, llm_seeds — NOT data/nhanes/)"
    echo "  results/         (all method outputs, summaries, CIs, figures)"
    echo "  cluster_results/ (SLURM job outputs)"
    echo ""
    echo "data/nhanes/ (downloaded XPT files) is preserved."
    echo "Jobs will be submitted immediately after. Each CPU job regenerates"
    echo "its own modeling CSV via run_pipeline.py before running methods."
    echo ""

    if [[ "$DRY_RUN" == "1" ]]; then
        echo "[dry-run] No files deleted. Continuing to dry-run job submission..."
        echo ""
    else
        read -r -p "Type YES to confirm purge and resubmit: " confirm
        if [[ "$confirm" != "YES" ]]; then
            echo "Aborted."
            exit 1
        fi
        # Delete everything inside data/ except the nhanes/ subdirectory (XPT files are
        # slow to re-download and are not regenerated by the pipeline jobs).
        find data/ -mindepth 1 -maxdepth 1 ! -name 'nhanes' -exec rm -rf {} +
        rm -rf results/ cluster_results/
        mkdir -p data results cluster_results
        echo "Purge complete. Submitting jobs..."
        echo ""
    fi
fi

# ── Job submission ─────────────────────────────────────────────────────────────
PYTHON=/home/ofekvi/.conda/envs/biomarkers/bin/python

# Derive NHANES-eligible diseases from conf/nhanes.yaml disease_case_defs keys.
# A disease is active if its entry is a non-empty list of conditions (not a dict
# with excluded: true, and not an empty list).
NHANES_DISEASES=$($PYTHON -c "
import yaml
with open('conf/nhanes.yaml') as f:
    cfg = yaml.safe_load(f)
active = []
for k, v in cfg.get('disease_case_defs', {}).items():
    # v is a list of conditions (active) or a dict with excluded: true (inactive)
    if isinstance(v, list) and len(v) > 0:
        active.append(k)
print(' '.join(active))
")

# Fake ID counter stored in a temp file so subshells share it.
_ID_FILE=$(mktemp)
echo "10000" > "$_ID_FILE"
trap 'rm -f "$_ID_FILE"' EXIT

# _submit <label> [sbatch args...]
# Prints the submitted job ID to stdout; prints a status line to stderr.
_submit() {
    local label=$1; shift
    if [[ "$DRY_RUN" == "1" ]]; then
        local id=$(( $(cat "$_ID_FILE") + 1 ))
        echo "$id" > "$_ID_FILE"
        echo "[dry-run] sbatch $*" >&2
        echo "$id"
    else
        local jid
        jid=$(sbatch --parsable "$@")
        echo "  [$label] job $jid" >&2
        echo "$jid"
    fi
}

for file in "$CONF_DIR"/*.yaml; do
    disease=$(basename "$file" .yaml)
    echo ""
    echo "=== $disease ==="

    # 1. GPU job — MedGemma generate
    gpu_id=$(_submit "GPU $disease" \
        --export=DISEASE="$disease",SPLIT_SALT="$SPLIT_SALT" \
        medgemma_generate.sbatch)
    [[ "$DRY_RUN" == "1" ]] && echo "  → GPU job ID: $gpu_id"

    # 2. CPU job — depends on GPU finishing
    #    When --purge was used, this job also runs run_pipeline.py first
    #    to regenerate the modeling CSV before any method scripts run.
    cpu_id=$(_submit "CPU $disease" \
        --dependency=afterok:"$gpu_id" \
        --export=DISEASE="$disease",SPLIT_SALT="$SPLIT_SALT" \
        pipeline_cpu.sbatch)
    [[ "$DRY_RUN" == "1" ]] && echo "  → CPU job ID: $cpu_id (dependency: afterok:$gpu_id)"

    # 3. Post-compute — CIs, NHANES eval, EHRSHOT eval, dashboard, forest plot
    skip_nhanes=0
    [[ " $NHANES_DISEASES " != *" $disease "* ]] && skip_nhanes=1

    post_id=$(_submit "POST $disease" \
        --dependency=afterok:"$cpu_id" \
        --export=DISEASE="$disease",SKIP_NHANES="$skip_nhanes",SKIP_EHRSHOT=0,NHANES_DIR="$NHANES_DIR",EHRSHOT_KEY_FILE="$EHRSHOT_KEY_FILE" \
        post_compute.sbatch)
    [[ "$DRY_RUN" == "1" ]] && echo "  → POST job ID: $post_id (dependency: afterok:$cpu_id, skip_nhanes=$skip_nhanes, skip_ehrshot=0)"
done

echo ""
echo "Done submitting all jobs."
